"""Audit facade used by the whole app: append to the tamper-evident log, then run monitoring.

Event types (spec sections 5, 15, 32):
  AUTH_LOGIN_SUCCESS, AUTH_LOGIN_FAILED, AUTH_LOGOUT, AUTH_TOKEN_REFRESHED, REFRESH_TOKEN_REUSE,
  MFA_ENROLLED, MFA_DISABLED, AUTH_SETUP, AUTHZ_DENIED,
  USER_CREATED, USER_ROLE_CHANGED, USER_STATUS_CHANGED,
  SEARCH_STARTED, SEARCH_QUERY_CREATED, SEARCH_EXECUTED, SEARCH_RESULTS_RECEIVED, CANDIDATE_CREATED,
  SEARCH_COMPLETED, SEARCH_FAILED, SEARCH_VIEWED, EVIDENCE_VIEWED, CANDIDATE_FEEDBACK, EVIDENCE_QUESTION,
  CASE_CREATED, CASE_UPDATED, CASE_VIEWED, CASE_DELETED, CASE_ACCESS_GRANTED, CASE_ACCESS_REVOKED,
  ADMIN_CASE_ACCESS, BREAK_GLASS_REQUESTED, BREAK_GLASS_APPROVED, BREAK_GLASS_DENIED,
  INCIDENT_CREATED, INCIDENT_UPDATED, EVIDENCE_CAPTURED, EVIDENCE_DOWNLOADED, EVIDENCE_INTEGRITY_VERIFIED,
  EVIDENCE_INTEGRITY_FAILED, ANALYSIS_STARTED, ANALYSIS_COMPLETED,
  REPORT_GENERATED, REPORT_EXPORTED, AUDIT_VIEWED, AUDIT_VERIFIED, AUDIT_CHAIN_BROKEN,
  SECURITY_EVENT_UPDATED, CALIBRATION_FITTED, RETENTION_PURGE, DATA_DELETED
"""
from ..core import audit_store
from . import monitoring


def record(event_type: str, **kw) -> dict:
    event = audit_store.append(event_type, **kw)
    monitoring.check(event)
    return event
